[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"
  RUBY_VERSION = "2.7.1 2.6.2"
[[plugins]]
  package = "netlify-plugin-gatsby-cache"
