backend:
  name: git-gateway
  branch: master

media_folder: src/pages/img

collections:
  - name: "item"
    label: "Art Items"
    folder: "src/pages/art-items"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "About", name: "about", widget: "text"}
      - {label: "Artist Notes", name: "artistNotes", widget: "text"}
      - {label: "Price", name: "price", widget: "number"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - label: "FeaturedImage"
        name: "featuredImage"
        widget: "custompathimage"
        customMediaPath: "../img/"
        rawMediaPath: "https://raw.githubusercontent.com/Dwaxy/art-site/tree/master/src/pages/img"
      