backend:
  name: git-gateway
  branch: master

media_folder: src/pages/img

display_url: https://elloron.art/store

collections:
  - name: "item"
    label: "Art Items"
    folder: "src/pages/store-items"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "About", name: "about", widget: "text"}
      - {label: "Artist Notes", name: "artistNotes", widget: "text", required: false}
      - {label: "Price", name: "price", widget: "string", required: false}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Info", name: "info", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      
      - label: "Type"
        name: "type" 
        widget: "list" 
        required: false
        feild:  
          - label: "Type Name" 
            name: "typeName" 
            widget: "string" 
            required: false

      - label: "Featured Image"
        name: "featuredImage"
        widget: "custompathimage"
        customMediaPath: "../img/"
        rawMediaPath: "https://raw.githubusercontent.com/Dwaxy/art-site/tree/master/src/pages/img"
      
      ##things to make item part of the arcive
      ## this separate normal store art posts from arcive posts that could just be text. In that case this must be false
      ## If the arcive item is also going to show in the store, then this must be true.
      
      
      ##common bools just so they are grouped with all the other bools. Happy family
      - {label: "Original", name: "original", widget: "boolean", default: true}
      - {label: "Store Highlight", name: "storeHighlight", widget: "boolean", default: false}
      
      ## based on this, if true, I somehow need to link pass a link to the store item from the arcive item, and vise versa
      
      ## archive_topic only shows in data if one is added. Could use this as is_archive_item instead as well as topic? 
      - {label: "Is Archive Item", name: "is_archive_item", widget: "boolean", default: false}
      
      ## This is so I use less queries
      - {label: "Is Store Item", name: "is_store_item", widget: "boolean", default: true}
      
      ##the html blog content of an arcive item. Only arcive items should have them
      
      - {label: "Body", name: "body", widget: "markdown", required: false}
      
      ##the list of topics an arcive item can have
  
      - lable: "Archive Topic" 
        name: "arcive_topic" 
        widget: "select"
        multiple: true
        required: false
        ## List of arcive topics
        options: 
          - Maps
          - Peoples
          - Locations
          - Creatures
          - History

      
  # - name: "archive-item"
  #   label: "World Archive Items"
  #   folder: "src/pages/art-items"
  #   create: true
  #   slug: "{{slug}}"
  #   fields:
  #     - {label: "Title", name: "title", widget: "string"}
  #     - {label: "Tags", name: "tags", widget: "list"}
  #     - {label: "Info", name: "info", widget: "string", required: false}
  #     - {label: "IsStoreItem", name: "original", widget: "boolean", default: true}
  #     - {label: "Store Highlight", name: "storeHighlight", widget: "boolean", default: false}
  #     - {label: "Publish Date", name: "date", widget: "datetime"}
  #     - {label: "Template Key", name: "templateKey", widget: "hidden", default: "art-pice"}
  #     - {label: "Is Archive", name: "is-archive", widget: "hidden", default: true}

  #     - label: "Type"
  #       name: "type" 
  #       widget: "list" 
  #       required: false
  #       feild:  
  #         - label: "Type Name" 
  #           name: "typeName" 
  #           widget: "string" 
  #           required: false

  #     - label: "Featured Image"
  #       name: "featuredImage"
  #       widget: "custompathimage"
  #       customMediaPath: "../img/"
  #       rawMediaPath: "https://raw.githubusercontent.com/Dwaxy/art-site/tree/master/src/pages/img"