backend:
  name: git-gateway
  branch: master

media_folder: src/pages/img

display_url: https://elloron.art/store

collections:
  - name: "item"
    label: "Art Items"
    folder: "src/pages/store-items"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Title", 
          name: "title", 
          widget: "string",
          hint: "Use Capitalization for Tte Title"
        }
      - {
          label: "About", 
          name: "about", 
          widget: "text", 
          # required: false,
          hint: "Used for SEO descriptions, does not show in store. Is needed to not have null in metadata"  
        }
      - {
          label: "Artist Notes", 
          name: "artistNotes", 
          widget: "text", 
          required: false,
          hint: "Add a story about the pice. If it is an archive item, hint at it's content, nothing more"  
      }
      - {
          label: "Price", 
          name: "price", 
          widget: "string", 
          required: false,
          hint: "Set to sold when item is gone / out of stock. Will show comission if taged with comission"
        }
      
      - {
          label: "Info", 
          name: "info", 
          widget: "string", 
          required: false, 
          hint: "Used for things like size, type"
        }
      - {label: "Publish Date", name: "date", widget: "datetime"}

      # ! ALL TAGS MEDIUM/TYPES AND NAMES MUST BE capitalised NOT LOWERCASE

      - label: "Tags" 
        name: "tags" 
        widget: "select" 
        required: false
        multiple: true
        hint: "Will put item under these categories if taged. Commission will move it to a special section and hide price"
        options: 
          - Commercial
          - Commission
          - Logos
          - Graphics
          - Maps
          - Landscapes
          - Mountains
          - Skys
          - Sketches
          - Abstract
          - Fantasy
          - Concept Art
          - Environment Concepts
      
      - label: "Type" 
        name: "type" 
        widget: "select" 
        required: false
        multiple: true
        hint: "Set item medium, add multible if medium is mixed"
        options: 
          - Watercolor
          - Digital
          - Oil
          - Acrylic
          - Pastel
          - Ink
          - Graphite

      - label: "Featured Image"
        name: "featuredImage"
        widget: "custompathimage"
        customMediaPath: "../img/"
        required: true
        rawMediaPath: "https://raw.githubusercontent.com/Dwaxy/art-site/tree/master/src/pages/img"
        hint: "Choose a good image, please. Clarify if it comes with frame if it has one in the image"
            
      ##common bools just so they are grouped with all the other bools. Happy family
      - {label: "Original", name: "original", widget: "boolean", default: true}
      - {label: "Store Highlight", name: "storeHighlight", widget: "boolean", default: false}
            
      ## This is so I use less queries
      - {
          label: "Is Store Item", 
          name: "is_store_item", 
          widget: "boolean", 
          default: true,
          hint: "Set to false if item is just an Archive item"
      }
      
      ##the html blog content of an archive item. Only archive items should have them

      - {
          label: "Is Archive Item", 
          name: "is_archive_item", 
          widget: "boolean", 
          default: false,
          hint: "Set to false if item is just a Store item"
        }
      
      - {
          label: "Body", 
          name: "body", 
          widget: "markdown", 
          required: false,
          hint: "Leave empty if NOT and Archive item"
        }
      
      - lable: "Archive Topic" 
        name: "archive_topic" 
        widget: "select"
        multiple: true
        required: false
        hint: "Set catergory/topic for archive page"
        options: 
          - Maps
          - Peoples
          - Locations
          - Creatures
          - History
      ##the list of topics an archive item can have
  
      # - lable: "Archive Topic" 
      #   name: "archive_topic" 
      #   widget: "select"
      #   multiple: true
      #   required: false
      #   ## List of archive topics
      #   options: 
      #     - Maps
      #     - Peoples
      #     - Locations
      #     - Creatures
      #     - History

      
  # - name: "archive-item"
  #   label: "World Archive Items"
  #   folder: "src/pages/art-items"
  #   create: true
  #   slug: "{{slug}}"
  #   fields:
  #     - {label: "Title", name: "title", widget: "string"}
  #     - {label: "Tags", name: "tags", widget: "list"}
  #     - {label: "Info", name: "info", widget: "string", required: false}
  #     - {label: "IsStoreItem", name: "original", widget: "boolean", default: true}
  #     - {label: "Store Highlight", name: "storeHighlight", widget: "boolean", default: false}
  #     - {label: "Publish Date", name: "date", widget: "datetime"}
  #     - {label: "Template Key", name: "templateKey", widget: "hidden", default: "art-pice"}
  #     - {label: "Is Archive", name: "is-archive", widget: "hidden", default: true}

  #     - label: "Type"
  #       name: "type" 
  #       widget: "list" 
  #       required: false
  #       feild:  
  #         - label: "Type Name" 
  #           name: "typeName" 
  #           widget: "string" 
  #           required: false

  #     - label: "Featured Image"
  #       name: "featuredImage"
  #       widget: "custompathimage"
  #       customMediaPath: "../img/"
  #       rawMediaPath: "https://raw.githubusercontent.com/Dwaxy/art-site/tree/master/src/pages/img"