backend:
  name: git-gateway
  branch: master

media_folder: src/pages/img

collections:
  - name: "item"
    label: "Art Items"
    folder: "src/pages/art-items"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "About", name: "about", widget: "text"}
      - {label: "Artist Notes", name: "artistNotes", widget: "text"}
      - {label: "Price", name: "price", widget: "number"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Info", name: "info", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
        
      - label: "Type"
        name: "type" 
        widget: "list" 
        required: false
        feild:  
          - label: "Type Name" 
            name: "typeName" 
            widget: "string" 
            required: false

      - label: "Featured Image"
        name: "featuredImage"
        widget: "custompathimage"
        customMediaPath: "../img/"
        rawMediaPath: "https://raw.githubusercontent.com/Dwaxy/art-site/tree/master/src/pages/img"
      